import Header from "@/components/Header"
import "./globals.css"
import { Inter } from "next/font/google"
import Provider from "@/components/Provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "CRUD App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='{inter.className}'>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
